apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-service-deployment
  namespace: stadiumos-system
  labels:
    app: express-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express-service
  template:
    metadata:
      labels:
        app: express-service
    spec:
      containers:
      - name: express-service
        image: gcr.io/google-deepmind-stadiumos/backend-express:1.0.0
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: stadiumos-db-secrets
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: express-service
  namespace: stadiumos-system
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: express-service
  type: ClusterIP
